<a href="https://colab.research.google.com/github/y4c6/master_thesis/blob/main/EJMR_toMatrix_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import json

In [ ]:
from google.colab import drive
# directory
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
with open('/content/gdrive/MyDrive/論文相關材料/EJMRpost_1_10.json', 'r') as f:
    data = json.load(f)

In [ ]:
print(data.keys()) #prints keys

dict_keys(['topic', 'posts'])


In [ ]:
data['topic'][:5]

['https://www.econjobrumors.com/topic/rbb-or-kari',
 'https://www.econjobrumors.com/topic/as-ian-americans-grapple-with-tide-of-attacks-%e2%80%98we-need-our-safety-back%e2%80%99',
 'https://www.econjobrumors.com/topic/russia-china-relations-are-strengthening',
 'https://www.econjobrumors.com/topic/just-found-out-that-its-possible-to-major-in-human-resources',
 'https://www.econjobrumors.com/topic/karen-and-zhang-get-married']

## asian-related posts selected by topic

In [ ]:
asian_target = ['asian', 'asia', 'china', 'chinese', 'korea', 'korean', 'japan', 'japanese', 'taiwan', 'taiwanese', 'east']



# initialize an empty list to store the indexes
asian_topic_idx = []

# iterate over the topics list
for i, topic in enumerate(data['topic']):
  # check if any of the target words are in the current topic
  if any(word in topic for word in asian_target):
    # if the target word is found, append the index to the indexes list
    asian_topic_idx.append(i)

print(asian_topic_idx[:15])
'''
for i in range(len(data['topic'])):
  for j in asian_target:
    if j in data['topic'][i]:
      asian_related.append(1)
    else:
      asian_related.append(0)
'''        


[2, 23, 44, 69, 79, 110, 129, 154, 158, 215, 232, 243, 265, 283, 288]


"\nfor i in range(len(data['topic'])):\n  for j in asian_target:\n    if j in data['topic'][i]:\n      asian_related.append(1)\n    else:\n      asian_related.append(0)\n"

In [ ]:
len(asian_topic_idx)

2597

In [ ]:
asian_topic_idx_01 = np.zeros(max(asian_topic_idx)+1)
asian_topic_idx_01[asian_topic_idx] = 1
asian_topic_idx_01

array([0., 0., 1., ..., 0., 0., 1.])

In [ ]:
def find_indices(list_to_check, item_to_find):
    indices = []
    for idx, value in enumerate(list_to_check):
        if value == item_to_find:
            indices.append(idx)
    return indices

asian_topic_idx = find_indices(asian_related, 1)
asian_topic_idx[-10]

77989

In [ ]:
len(list( dict.fromkeys(asian_topic_idx) )) # to see if there is duplicated posts

294

In [ ]:
len(asian_topic_idx) / len( data['posts']) # to see the ratio 

0.0324625

filtered out asian-posts

In [ ]:
asian_posts = [data['posts'][i] for i in asian_topic_idx]

word counts for asian_posts

In [ ]:
posts = [' '.join(i).lower() for i in asian_posts]

In [ ]:
print(type(posts), len(posts))
posts[0]

<class 'list'> 294


"not even accounting for indians. all the quant clubs at universities are majority asian, all majoring in computational finance / math / cs / financial engineering. is this the only way out if one majors in math and doesn't want to join academia or be a high school teacher? yeah, nvidia is more than 50% asian. i assume their engineering teams are 75% asian. chinese are in all the quant finance programs.\nso original. chinese are in all the quant finance programs.\nso original. your “criticism” shows how origjnal you are, mor/on. fundamental is better than quant these days, needs more creativity and pays more over time. chinese are in all the quant finance programs.\nso original. aren't you in quant? fundamental is better than quant these days, needs more creativity and pays more over time. define fundamental equity long/short, usually trading around earnings beats/misses. fundamental is better than quant these days, needs more creativity and pays more over time. stats or gtfo it's much

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Create a matrix using CountVectorizer
vectorizer = CountVectorizer(preprocessor = preprocess_text, 
                tokenizer = tokenize_and_remove_stopwords, 
                max_features = 10000)

In [ ]:
posts_matrix = vectorizer.fit_transform(posts)

# Print the matrix
print(posts_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## words counts

In [ ]:
data['posts'][0]

['Whose more of a dishonest cringe dooshbag?',
 'I love Karl. He’s very honest',
 'I love Karl. He’s very honest',
 'Perhaps your perception of his honesty is biased by your homo feelings of love for him, yes?',
 'Brunet the journalist went into hiding the second actual world events dominated the conversation because now no one on EJMR cares about tweet fights with woke VLRM academics',
 'Why the RBB abbreviation? Is it Rus Bed & Breakfast?',
 'Why the RBB abbreviation? Is it Rus Bed & Breakfast?',
 'I have absolutely no idea, but that is how he is referred to here.  I just assumed it somehow made sense to his lQ = 60 fan base.',
 'I prefer to refer to him as RusTardFest.',
 'Karlito >>>>>>>> rbb',
 'Karl is a dvmb ngr',
 'RBB is a bro <3',
 'both are !d!ots',
 'both are !d!ots',
 'This',
 's/t/f/u chad',
 'RBB and Karl is the reason why I come here. I love ejmr characters',
 'RBB >>>> Karl.',
 'RBB has awful taste, but is a bro.',
 'Why are they at odds?']

In [ ]:
posts = [' '.join(i).lower() for i in data['posts']]

In [ ]:
print(type(posts), len(posts))
posts[0]

<class 'list'> 80000


'whose more of a dishonest cringe dooshbag? i love karl. he’s very honest i love karl. he’s very honest perhaps your perception of his honesty is biased by your homo feelings of love for him, yes? brunet the journalist went into hiding the second actual world events dominated the conversation because now no one on ejmr cares about tweet fights with woke vlrm academics why the rbb abbreviation? is it rus bed & breakfast? why the rbb abbreviation? is it rus bed & breakfast? i have absolutely no idea, but that is how he is referred to here.  i just assumed it somehow made sense to his lq = 60 fan base. i prefer to refer to him as rustardfest. karlito >>>>>>>> rbb karl is a dvmb ngr rbb is a bro <3 both are !d!ots both are !d!ots this s/t/f/u chad rbb and karl is the reason why i come here. i love ejmr characters rbb >>>> karl. rbb has awful taste, but is a bro. why are they at odds?'

In [ ]:
all_posts = ' '.join(posts)

In [ ]:
print(len(all_posts), type(all_posts))

140456842 <class 'str'>


In [ ]:
import nltk
nltk.download('punkt') #this is download for tonkenizer
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import string
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Define a function to preprocess text
def preprocess_text(text):
  # Lowercase all characters
  text = text.lower()

  # Remove URLs
  text = re.sub(r'https?://\S+', '', text)

  # Remove digits
  text = text.translate(str.maketrans('', '', string.digits))

  # Remove punctuation
  text = text.translate(str.maketrans('', '', string.punctuation))

  return text

# Define a function to tokenize and remove stopwords from text
def tokenize_and_remove_stopwords(text):
  # Tokenize the article
  text_tokens = word_tokenize(text)

  # Load English stopwords
  stop_words = set(stopwords.words('english'))

  # Remove stopwords
  tokens = [token for token in text_tokens if token not in stop_words]

  return tokens


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Create a matrix using CountVectorizer
vectorizer = CountVectorizer(preprocessor=preprocess_text, 
                tokenizer=tokenize_and_remove_stopwords, 
                max_features = 10000) # 80000, run out of ram

NameError: ignored

In [ ]:
posts_matrix = vectorizer.fit_transform(posts)

# Print the matrix
print(posts_matrix.toarray())

In [ ]:
posts_matrix.shape

(80000, 10000)

In [ ]:
import pickle
with open('posts_matrix_test.pkl','wb') as f:
  pickle.dump(pos#ts_matrix, f)

In [ ]:
tokens = [ cleaned_tokenize(posts[i]) for i in range(len(posts)) ]

NameError: ignored

In [ ]:
len(tokens)

80000

In [ ]:
from collections import Counter
counter = Counter(tokens)
counter.most_common(10000)

NameError: ignored

In [ ]:
# Out of memory
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(
    lowercase = True, 
    analyzer = 'word',
    stop_words = 'english',
    ngram_range = (1, 1),
    max_features = 10000
    )
X = vectorizer.fit_transform(tokens)
X = X.toarray()

In [ ]:
from sklearn.linear_model import LassoCV

clf = LassoCV()
clf.fit(posts_matrix, np.array([1]* len(asian_topic_idx)))
print(clf.coef_[:10])

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:609: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0, tolerance: 0.0
  model = cd_fast.sparse_enet_coordinate_descent(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:609: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0, tolerance: 0.0
  model = cd_fast.sparse_enet_coordinate_descent(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:609: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0, tolerance: 0.0
  model = cd_fast.sparse_enet_coordinate_descent(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:609: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterati

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:609: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0, tolerance: 0.0
  model = cd_fast.sparse_enet_coordinate_descent(


In [ ]:
clf.coef_[clf.coef_!=0]

array([], dtype=float64)

In [ ]:
pip install doubleml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 126 kB 6.1 MB/s 


In [ ]:
import doubleml as dml
from sklearn.base import clone

from sklearn.ensemble import RandomForestRegressor

learner = RandomForestRegressor(n_estimators=100, max_features=20, max_depth=5, min_samples_leaf=2)
ml_g = learner
ml_m = learner
dml_plr_obj = dml.DoubleMLPLR(obj_dml_data, ml_g, ml_m)
dml_plr_obj.fit().summary

In [ ]:
from doubleml.datasets import make_plr_CCDDHNR2018
obj_dml_data = make_plr_CCDDHNR2018(alpha=0.5, n_obs=500, dim_x=20)

In [ ]:
type(obj_dml_data)

doubleml.double_ml_data.DoubleMLData